### ISSUE TITLE
ZIM backend : put the article content inside an iframe, because it sometimes displays over the bottom bar (instead of under)

### ISSUE THREAD

**Issue by mossroy** [mossroy/evopedia-html5#105]
It seems to depend on the ZIM file

**Comment by kelson42** [comment]
A example with:
* screenshot
* article title
* ZIM file name
... would really help.

**Comment by mossroy** [comment]
Here is an example : 
- use http://download.kiwix.org/zim/wikipedia/wikipedia_en_all_simple_nopic_2015-02.zim
- open the ".htaccess" article (it's in the list if you make a search without typing anything)

The article is displayed correctly, but it overlaps the bottom bar :
![2015-05-03-19-40-13](https://cloud.githubusercontent.com/assets/890923/7446100/192d02a8-f1cd-11e4-93b0-9fa46e82f3c4.png)



If you scroll down the article to its very end, the bottom bar gets visible :
![2015-05-03-19-40-27](https://cloud.githubusercontent.com/assets/890923/7446101/193e3f00-f1cd-11e4-8013-f16f1e4cffa2.png)

It's certainly a CSS issue, which is not surprising as the CSS had been designed for articles from Evopedia archives (which are probably processed a bit differently)

**Comment by kelson42** [comment]
Thank you for the screenshot. If the UI makes assumptions about the HTML content, then this might be the cause, but does it?

**Comment by mossroy** [comment]
There are aminly 3 CSS in this app : 
- app.css handles the rendering of the UI. It does not make any assumptions on the article content
- bootstrap*.css are handling the bootstrap parts of the UI. It does not make any assumptions on the article content either
- mediawiki-main.css does make assumptions on the article content (I mean : on its structure)

I found where it comes from : in mediawiki-main.css, line 63, the article content is assigned a z-index of 2.
If I disable this CSS property, the bottom bar reappears.

Now we need to find a way to do this properly, and in a compatible way for both archive formats.

Regarding CSS, I see that the article content references a CSS (and also a javascript) that it does not currently find : 
    <link rel="stylesheet" href="../-/s/style.css">
    <script src="../-/j/head.js"></script>
Maybe, when using ZIM archives, we should use this style.css instead of mediawiki-main.css?
Do you know where can we find these files?

**Comment by kelson42** [comment]
Two remarks about these last information:
* We have currently massive problems during the ZIM file generation to replace the whole Mediawiki resourceLoader infrastructure. To fix this, this would need a dedicated javascript effort to fix mwoffliner. Anyway, that explains the problems with CSS/JS you have remarked I guess.
* We focus on Wikipedia/Mediawiki but in fact we have ZIM files of very different content. IMO the app should be able to work with any kind of content... But I don't know if this is easy or not to do, at least Kiwix is conceived following that rule.
* For the z-index problem, why not just putting z-index: 10 to the whole UI (so we are sure this is displayed over the rest)?

**Comment by mossroy** [comment]
That made 3 remarks, not 2 ;-)

I did not work on the creation process of evopedia archives at all. Maybe @peter-x knows more about it. I suppose he faced the same issues : that would be interesting to know how they were dealt with. In any case, I know it was not perfect either.

I agree with you about ZIM file format : we should try to avoid wikipedia/mediawiki-specific code.
If I follow this, I should completely remove the mediawiki-main.css. I tested and it fixes the bottom bar issue.
But there is a big drawback : the layout of wikipedia articles is lost.

For example, an article that would look like this with the wikimedia CSS : 
![capture du 2015-05-03 22 40 19](https://cloud.githubusercontent.com/assets/890923/7446831/9ed9789c-f1e5-11e4-940b-a85ca7f0f16c.png)
... will look like this : 
![capture du 2015-05-03 22 40 27](https://cloud.githubusercontent.com/assets/890923/7446835/ad467dc6-f1e5-11e4-907d-b1cdb49dded2.png)

I think we need a way to keep applying some kind of wikimedia CSS (only when it's a wikimedia article). How do you deal with that in Kiwix?

**Comment by kelson42** [comment]
Everything (CSS included) should be stored in ZIM files. ZIM files should rely on nothing outside the ZIM file itself. In case of Evopedia (and Evopedia native format), it seems that part of the content stylesheet is static - in the reader itself. I would recommend to simply avoid to use mediawiki-main.css if a ZIM format/file is in use.

**Comment by mossroy** [comment]
That makes sense.
But where should we find the CSS file(s) for wikimedia articles inside a ZIM file?
Is it the style.css file that it currently does not find?
```
    <link rel="stylesheet" href="../-/s/style.css">
    <script src="../-/j/head.js"></script>
```
(this code excerpt was in a previous comment, but did not show up because I did not escape it : I just fixed it)

**Comment by kelson42** [comment]
We are here deep enough in the detail to let me say: I'm not aware enough about how works the FFOS SDK/app to give a clear answer to this question.

In all cases I'm aware of, the Kiwix software/app has a HTML render widget which simply displays the HTML page/article/content (with the CSS dependencies if needed).This wihtout needing any additional manual work: the CSS/CSS/pictures/videos/... HTML dependencies should simply be loaded automatically.

That said, I don't know in a FFOS app if the app UI render widget is the same like the one of the content. If yes, then you probably have to use an iframe because otherwise it will be pretty quickly a nightmare IMO...

**Comment by mossroy** [comment]
Basically, a Firefox OS application should be considered as a web page running in a browser. There is no kind of widget or SDK.
In our case, we only use one specific javascript API (DeviceStorage) that lets us access the SD-card.
Everything else is purely HTML5/javascript, and runs the same on a desktop Firefox (or another recent browser). That's why you can develop and test on a desktop Firefox (by selecting manually the ZIM file instead of making use of the DeviceStorage API)

In any case, my question was more about the ZIM file format. As it contains all the dependencies, including the CSS, I'm just wondering where to find it technically in the ZIM file. I suppose it's the "-/s/style.css" file.

There seems to be a difference in the article content between ZIM and Evopedia archives : Evopedia stores only the html body (what's inside the <body> </body>), where ZIM stores a complete HTML file.
I don't like iframes but it might be something to consider if necessary.

In any case, keep in mind that there is a major difference with Kiwix applications : there is no server listening to HTTP requests and sending content (even if Douglas told me he was working on something like this).
We read the article content from the archive, then dynamically inject it in a <div> inside the current HTML page. It there are external resources used or linked in the article content, they need to be found (with jQuery), and replaced by their content (or by javascript calls). It's done this way for hyperlinks between articles, for math formulas, etc.
So the CSS and JS referenced in an article will have to be separately retrieved, and manually injected in the DOM.
That might sound like a drawback, but it makes it very portable, without any running server.

The ServiceWorker API might change that, but its implementation is still in progress in the browsers.

**Comment by kelson42** [comment]
A few remarks (I don't give any number anymore ;) :
* Kiwix app does not work with a HTTP server (even if we propose an HTTP server - as an option). Here it seems to me Evopedia and Kiwix both work in the same (and IMO right) way.
* You can not do any assumption about where is (or are) the CSS. They should be in the "-" namespace, but this can have any kind of name and in fact, this should also work if the CSS is in the "A" namespace. The only way to detect it, is to parse the DOM (and also interpret the JS in case of dynamically loaded CSS) - but please don't.
* I confirm, after reading your last comment, that I don't see how this can work *in any case* without an iframe. Otherwise UI&content CSS/JS will mix up.

To work correctly with ZIM files, IMO the shorter way is:
* Configuring a custom protocol (should be feasible with FFOS) following a scheme like this: zim://<ZIM_ID>/<ZIM_URL>
* Create an iframe to display the content.
With this we will have then only to tell the iframe to load a zim:// url and all the rest will work alone (and most important without having to parse the content DOM)

**Comment by kelson42** [comment]
So, I have asked around a little bit about "custom protocol handler" and it seems that this does not exists.

But, it looks like there is a way to catch all http calls with new service workers:
https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorker_API/Using_Service_Workers

**Comment by mossroy** [comment]
Yes, Service Workers would really be a clean and efficient way to do what we want. I had mentioned it above.
Unfortunately, they seem to be only partially implemented, with limited debug tools, and not enabled by default in Firefox.
So I think it's too early to use them.
Or at least we need a fallback that works without Service Workers.
What we did for Evopedia backend was to parse the DOM content with jQuery, and modify what needed to be. It's far less elegant than Service Workers, and might miss some links if we don't handle them properly. But it works in almost all cases for Evopedia.

Regarding iframes, you're probably right. The concern I have is the communication between the iframe and its parent. It's possible in many ways but, there are many caveats.
Thanks for your explanations about Kiwix and ZIM format : it makes things clearer for me

**Comment by mossroy** [comment]
I played a little bit with the article content in an iframe. I've pushed that in a separate branch for now, if you want to have a look : https://github.com/mossroy/evopedia-html5/tree/article_in_iframe

Here are the good news :
- It was not complicated to setup
- I did not face communication issues between the iframe and its parent
- It would certainly be the best way to apply the ZIM CSS/JS files without interfering with the rest of the screen (like you said)
- I managed to apply the wikimedia CSS only for Evopedia archives, and to inject custom test CSS for ZIM archives

The bad news are : 
- Using an iframe gives scrolling issues. An iframe has a height and a width. If the content does not fit in it, you have scrolling bars in it. So only the content of the iframe is scrolling, not the whole user interface. This wastes some space on the screen IMO, because the menus/search form will not naturally disappear when the user scrolls down : they will keep using some space, that could be better used for the article content
- I also have difficulties to make the iframe use the whole height. But I did not spend a lot of time on that

If the goal is to apply a CSS only on the article content, there might be another approach to test : keeping the article content in a div (without iframes), and using scoped CSS https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style
I'll try to have a look at that. It might work for CSS. But, if we keep the article in a div, there might still be issues for some javascript referenced in the article : the DOM will include all the UI, not only the article itself. So, depending on what the javascript does, it might still interfere with the UI.

In any case, I'll need to read the CSS, JS and image files from the ZIM file. I don't know if it's currently possible with the ZIM backend of @peter-x , and how to do it. I opened issue #115 for that

**Comment by kelson42** [comment]
Nice to see it works with iframes, but of course there is still things to fix and this might be pretty much time consuming. The problem with the topbar can probably be fixed with catching iframe scrolling events, but it seems to me these kind of problems is pretty usual for people working on full HTML mobile app (Wikimedia Foundation people had similar one with cordova). As a side note, on Android, we don't hide (dynamically) the topbar and this is not a blocking problem for users.

I have got my ZTE Open C but I won't probably have time to hack a lot around it until the hackathon in June. So, for me next hacking session with FFOS will be with you in Lyon.

My belief is that there is probably no serious way out without service workers. Consequently, on my side, I won't probably try a lot to deal with other workarounds and will start directly with service workers even if currently not all FFOS devices have them. It would be in particular interested to know if we need something specific (a sw feature) which is not yet implemented in FFOS runtime (maybe what is already there is good enough for us) so we can report this to FFOS team.

**Comment by mossroy** [comment]
Yes there are still plenty of things to investigate. Exciting but also time-consuming :-)

Regarding these recent APIs, we'll have to deal with browser/version compatibility, which will not be easy : 
For Scoped CSS : http://caniuse.com/#feat=style-scoped
For Service Workers : http://caniuse.com/#feat=serviceworkers and https://developer.mozilla.org/fr/docs/Web/API/ServiceWorker_API/Using_Service_Workers

**Comment by mossroy** [comment]
This is done, but I opened #120 for several needed enhancements. Because, for now, the article content is restricted in a too small area

**Comment by kelson42** [comment]
Awesome! I have to test it again. Do we somewhere a list of blockers for a first release?

**Comment by mossroy** [comment]
If you want to test this (without service workers), use the article_in_iframe branch. It should work on desktop browser and your Firefox OS device.
I had put the main features in the v2.0 roadmap : https://github.com/mossroy/evopedia-html5/milestones/v2.0
