### ISSUE TITLE
ZIM backend : some titles can not be found

### ISSUE THREAD

**Issue by mossroy** [mossroy/evopedia-html5#122]
Example in the Ray Charles archive : "You got the right one baby" article can not be found if you put "y" or "you" as the prefix.
But it is in the ZIM file, and it appears if you put "u" as the prefix (until #104 is fixed...)

**Comment by kelson42** [comment]
One of the root cause is that URLs proposed in the suggestions are not escaped correctly. For example a suggestion for the article "A & C Black" will lead to an URL with "title=A%20&%20C%20Black". It should be "title=A%20%26%20C%20Black". The ZIM file itself has URLs which are not urlencoded, but for the transport over HTTP, this needs to be done (encoding in frontend and decoding in backend).

**Comment by mossroy** [comment]
Are you talking about the URL displayed by the browser? In this case, I'm not so sure it is related. I manually set this URL in pushBrowserHistoryState() (in app.js), but I don't think it's even used afterwards. I would have to check.
The title of an article in the list is serialized with other title attributes in a "titleid" attribute of the <a> tag, not in a URL
