### ISSUE TITLE
Refreshing the page makes the app loosing all configuration

### ISSUE THREAD

**Issue by kelson42** [mossroy/evopedia-html5#125]
This happens by clicking on the browser reload/refresh button (on Chrominum).
To my opinion:
* The ZIM file should be still loaded
* The last page should be also loaded

Switching between tabs make also to loose the current article.

Using a cookie should allow to fix this easily.

**Comment by mossroy** [comment]
Regarding the "loss" of selected archive on a refresh :
On desktop browsers, that's true on Chromium/Chrome, but not on Firefox (which keeps the files, but only during the browser session). I'm afraid I won't be able to change this behavior, because AFAIK, a browser won't let me populate an input type=file (for security reasons. See very complete explanations here : http://stackoverflow.com/questions/20537696/remember-and-repopulate-file-input ).
On Firefox OS, there is no such issue because the files are accessed through the DeviceStorage API (with user consent), and I keep the selected archive in a cookie.

Regarding keeping the last article after closing/reopening or switching between sections (tabs) of the UI : yes, that can certainly be done with a cookie. I opened #127 for that, and I close this one
